version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "08:00" # Does not support ADST, will always be in AEST
    timezone: "Australia/Melbourne"
  allow:
  # direct dependencies only
  - dependency-type: "direct"
  commit-message:
    # Prefix all commit messages with "deps: "
    prefix: "deps"
  open-pull-requests-limit: 10

  # Create a group of dependencies to be updated together in one pull request
  groups:
    # The following groups are to updated to minor and patch versions only
    # major updates should be handled manually, as there can be breaking changes
    capacitor:
      patterns:
      - "@capacitor*"
      update-types:
      - "minor"
      - "patch"

    ionic:
      patterns:
      - "@ionic*"
      update-types:
      - "minor"
      - "patch"

    types:
      patterns:
      - "@types*"

    eslint:
      patterns:
      - "eslint*"
      - "@eslint*"
      - "typescript-eslint"
      update-types:
      - "minor"
      - "patch"

  ignore:
  - dependency-name: "@capacitor*"
    update-types: [ "version-update:semver-major" ]
  - dependency-name: "@capawesome*"
    update-types: [ "version-update:semver-major" ]
  - dependency-name: "@ionic*"
    update-types: [ "version-update:semver-major" ]
