version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "friday"
    time: "08:00" # Does not support ADST, will always be in AEST
    timezone: "Australia/Melbourne"
  allow:
  # direct dependencies only
  - dependency-type: "direct"
  commit-message:
    # Prefix all commit messages with "deps: "
    prefix: "deps"
  open-pull-requests-limit: 10

  # Create a group of dependencies to be updated together in one pull request
  groups:
    all:
      patterns:
      - "*"
